http:
  port: 8080
  adminPort: 8081
  requestLog:
    console:
      enabled: false

logging:
  console:
    timeZone: America/Sao_Paulo
  loggers:
    pessoa: DEBUG
    org.apache.zookeeper: WARN
    com.netflix.config: ERROR

database:
  driverClass: org.postgresql.Driver
  user: postgres
  password: root
  url: jdbc:postgresql://localhost/pessoa

httpClient:
  timeout: 900ms

curator:
  ensemble:
    namespace: descoberta

servicoEndereco:
  nome: endereco
  versao: dev

servicoContato:
  nome: contato
  versao: dev
