http:
  port: 0
  adminPort: 0
  requestLog:
    console:
      enabled: false

logging:
  console:
    timeZone: America/Sao_Paulo
  loggers:
    gp: DEBUG
    org.apache.zookeeper: WARN
    com.netflix.config: ERROR

database:
  driverClass: org.postgresql.Driver
  user: postgres
  password: root
  url: jdbc:postgresql://localhost/gp

httpClient:
  timeout: 900ms

curator:
  ensemble:
    namespace: descoberta
